// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/index.tsx";
import * as $$0 from "./islands/Acordeon.tsx";
import * as $$1 from "./islands/CarouselIsland.tsx";
import * as $$2 from "./islands/Counter.tsx";
import * as $$3 from "./islands/MobileHeader.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/Acordeon.tsx": $$0,
    "./islands/CarouselIsland.tsx": $$1,
    "./islands/Counter.tsx": $$2,
    "./islands/MobileHeader.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
